spring:
  application:
    name: seekerhut
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.175:3306/seekerhut_tweet?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #host: 127.0.0.1
    #port: 6380
    password: 123456
    database: 1
    timeout: 1000
    prefix: forum

    sentinel:
      master: mymaster
      nodes:
        - 192.168.0.100:26380
        - 192.168.0.100:26381
        - 192.168.0.100:26382
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 5000
        min-idle: 1
  session:
    store-type: redis

mybatis:
  mapper-locations: classpath*:com/seekerhut/mySqlMapper/*.xml
  config-location: classpath:mybatis-config.xml

subRedisNodes:
  -
    a1: a1
    b1: b1
  - 
    a1: a2
    b1: b2

server:
  port: 8081