spring:
  application:
    name: seekerhut
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://198.13.57.152:3306/seekerhut?useSSL=false
    username: seekerhut
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 198.13.57.152
      port: 27017
      database: seekerhut
  redis:
    host: 198.13.57.152
    port: 6379
    database: 1
    timeout: 1000
    prefix: forum
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        max-wait: 5000
        min-idle: 1
  session:
    store-type: redis

mybatis:
  mapper-locations: classpath*:com/seekerhut/mySqlMapper/*.xml
  config-location: classpath:mybatis-config.xml

server:
  port: 8080